name: Gatsby Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: gh-pages
          gatsby-args: --prefix-paths
        env:
          REACT_APP_REDDIT_ID: ${{ secrets.REACT_APP_REDDIT_ID }}
          REACT_APP_REDDIT_SECRET: ${{ secrets.REACT_APP_REDDIT_SECRET }}
          REACT_APP_CALLBACK_URL: ${{ secrets.REACT_APP_CALLBACK_URL }}
